"""empty message

Revision ID: fbd52897fa5b
Revises: 87886f775e1b
Create Date: 2018-09-12 16:44:10.083073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd52897fa5b'
down_revision = '87886f775e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_uid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['create_uid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('create_uid')

    # ### end Alembic commands ###
